### ISSUE TITLE
[BUG] RingApi devices class

### ISSUE THREAD

**Issue by vincentr** [KoenZomers/RingApi#19]
**Describe the bug**
The latest Devices class has invalid property types. Attached are changes to class files.

**To Reproduce**
ConsoleApp crashes with -list param

**Versions (please complete the following information):**
- Ring API version: 0.5.0.1

[RingApiFix.zip](https://github.com/KoenZomers/RingApi/files/9620388/RingApiFix.zip)

**Comment by KoenZomers** [comment]
If you're still interested in this, can you try it again with the latest version and see if it works for you now?

**Comment by vincentr** [comment]
Using API version 0.5.2.0 appears to resolve this.
