### ISSUE TITLE
GetDoorbotsHistory(limit) max of 100?

### ISSUE THREAD

**Issue by NikoKatsaras** [KoenZomers/RingApi#2]
Hi Koen,

Thank you for taking the time to write this API!  I'm actually returning my Ring doorbell because it's awful in too many ways to list here and I have replaced it with a much better camera.  Much to my dismay, like so many other customers, I was shocked and frustrated that Ring doesn't allow downloading of the videos from their website.  (another reason to dump Ring)  

After tinkering around a while, I finally figured out how to actually use your API to download all of the files and here is what I came up with.  Unfortunately, even when I set the limit at 300, it still only downloads 100 videos.  Is there any way to download more than 100?  Thanks in advance!

public async Task GetDoorbotsHistoryDownloadWithLimitTest()
        {
            var limit = 300;
            int count = 0;
            var session = new Api.Session(Username, Password);
            await session.Authenticate();
            var doorbotHistory = await session.GetDoorbotsHistory(limit);
            Console.WriteLine(doorbotHistory.Count);
            foreach(var uniqueID in doorbotHistory)
             {
                var videoID = doorbotHistory[count].Id;
                Console.WriteLine($"{videoID}");
                var fileName = System.IO.Path.GetTempPath() + videoID.ToString() + ".mp4";
                Console.WriteLine($"{count} {fileName}");
                await session.GetDoorbotHistoryRecording(videoID, fileName);
                count++;
             };
            Assert.IsTrue(doorbotHistory.Count > 0, "No doorbot history items returned");
            Assert.IsTrue(doorbotHistory.Count == limit, $"{doorbotHistory.Count} doorbot history items returned while {limit} were expected");
        }

**Comment by KoenZomers** [comment]
I did a test on this and it is a limitation on the Ring side of the API. Indeed whenever I request a higher limit than 100 items, it will still only return 100 items at most. This is unfortunately not something I can fix.

**Comment by KoenZomers** [comment]
Actually there is a way to get this done. I was reading up through my older e-mails I received on this API and I found someone who figured out a way to get the older records by adding &older_than=<id> to the query string. I.e.:

`https://api.ring.com/clients_api/doorbots/history?limit=100&older_than=6722758926558758000`

Where the ID, in this case 6722758926558758000, is the ID of the oldest one received in the first batch of 100 items. This will return you the next batch of 100. You can keep doing this trick to get next batches.

I'll see if I can put this in the API in an automated way.

**Comment by KoenZomers** [comment]
Implemented and fixed in version 0.3.1.0: https://www.nuget.org/packages/KoenZomers.Ring.Api/0.3.1
