### ISSUE TITLE
[BUG] Brief description

### ISSUE THREAD

**Issue by chrisstuart-cl** [KoenZomers/RingApi#23]
**Describe the bug**
It's no longer possible to authenticate. This line of code fails in the unit tests.
`var oAuthResponse = await _httpUtility.FormPost(RingApiOAuthUrl,  oAuthformFields, headerFields);`

**To Reproduce**
Run the unit tests.

**Expected behavior**
Unit tests should pass. There appears to have been an API change within the last few days.

**Versions (please complete the following information):**
Latest version from github.

**Comment by quiggles** [comment]
I am also encountering the same issue with authentication.

**Comment by KoenZomers** [comment]
Check https://github.com/KoenZomers/RingApi/issues/24
