### ISSUE TITLE
[BUG] Session.Authenticate receives 401

### ISSUE THREAD

**Issue by ronwarner** [KoenZomers/RingApi#25]
**Describe the bug**
This may or may not be related to #24 
When I instantiate a `Session` and call its `Authenticate` method, a `WebException` is thrown with the following message:

The remote server returned an error: (401) Unauthorized.

**To Reproduce**
1. Instantiate a `KoenZomers.Ring.Api.Session` by passing a valid username and password to the `Session(string username, string password)` constructor.
2. Call `Authenticate()` on the `Session`
3. See contents of resulting `System.Net.WebException`

**Expected behavior**
On an account protected with 2FA, a `KoenZomers.Ring.Api.Exceptions.TwoFactorAuthenticationRequiredException` should be thrown, allowing the program a chance to acquire a 2FA token.

**Versions (please complete the following information):**
- Ring API version: 0.4.3.2

**Comment by ronwarner** [comment]
Oops.  I was using an older branch that had the 0.4.3.2 NuGet package.  Now that I've switched to using 0.5.0.1, the exception being thrown is of type `KoenZomers.Ring.Api.Exceptions.AuthenticationFailedException`.  So perhaps this is indeed the same as issue #24

**Comment by KoenZomers** [comment]
Check https://github.com/KoenZomers/RingApi/issues/24
