### ISSUE TITLE
Issue Getting Ring Devices

### ISSUE THREAD

**Issue by TylerEspo** [KoenZomers/RingApi#3]
Error converting value "unknown" to type 'KoenZomers.Ring.Api.Entities.DeviceStatus'. Path 'stickup_cams[0].led_status', line 1, position 7755.'

```C#
static void Main(string[] args)
        {
            Task.Run(() =>
            {
                Begin();
            });

            Console.ReadLine();
        }


        static async void Begin()
        {
            var session = new Session("XXXXX", "XXXXX");

            await session.Authenticate();

            var devices = await session.GetRingDevices();

            foreach (var device in devices.StickupCams)
            {
                Console.WriteLine(device.Description);
            }
        }
```

**Comment by KoenZomers** [comment]
Thanks for reporting this @TylerEspo. Can you try it again with [version 0.4.0.3](https://www.nuget.org/packages/KoenZomers.Ring.Api/0.4.0.3) which applies less strict JSON parsing to see if this resolves your case as well?

**Comment by KoenZomers** [comment]
Closing issue as no response has been received
