### ISSUE TITLE
Email with plus symbol fails to authenticate

### ISSUE THREAD

**Issue by insane4sure** [KoenZomers/RingApi#5]
My primary account is two-factor protected.  I created a shared account to consume the API.  Something like "primaryemail+ringapi@gmail.com".  Gmail and Ring.com and the Ring App (iPhone) all allow this, but the API fails to authenticate.  Probably something with url encoding.

**Comment by KoenZomers** [comment]
Thanks for reporting this @insane4sure. I'm looking into it.

**Comment by KoenZomers** [comment]
Fixed in [version 0.4.0.1](https://www.nuget.org/packages/KoenZomers.Ring.Api/0.4.0.1)
